# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2008-2014
  project: ab_booking
  version: 0.7
  release: 0.6.14
  latex_documents:
  - - Index
    - ab_booking.tex
    - ab\_booking
    - Alexander Bigga
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
